name: CI/CD Pipeline for Telegram Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and Static Analysis
        run: |
          pip install flake8 pylint
          flake8 --exclude=env --max-line-length=100 .
          pylint --errors-only *.py

      - name: Run Tests
        run: |
          python -m unittest discover -s tests

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Server
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          ssh user@server "git pull && systemctl restart telegram-bot.service"